version: "3.9"

services:
  naming-server:
    build: ./naming-server
    image: naming
    ports:
      - "8761:8761"
    networks:
      - currency-network

  currency-exchange:
    build: ./currency-exchange-service
    image: exchange
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      # SPRING reads env like this (UPPERCASE + _)
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka

  currency-conversion:
    build: ./currency-conversion-service
    image: conversion
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka

  api-gateway:
    build: ./api-gateway
    image: apigateway
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka

  currency-report:
    build:
      context: ./currency-report
      dockerfile: Dockerfile
    image: currency-report
    container_name: currency-report
    ports:
      - "8080:8080"   # host:container
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka


  currency-history:
    build:
      context: ./currency-history
      dockerfile: Dockerfile
    image: currency-history
    container_name: currency-history
    ports:
      - "8082:8082"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka


networks:
  currency-network:
    driver: bridge
